version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
      groups:
          actions:
              patterns: ["*"]
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
      versioning-strategy: "increase-if-necessary"
      ignore:
          - dependency-name: "@types/node"
            update-types: ["version-update:semver-major"]
      groups:
          npm-minor-and-patch:
              patterns: ["*"]
              update-types: ["minor", "patch"]
