#!/usr/bin/env bash

#
# Copyright (c) 2026 Michael Welter <me@mikinho.com>
#
# MIT License
#

#
# Git pre-commit hook
#

set -e

FILES=$(git diff --cached --name-only --diff-filter=ACMRTUXB | tr '\n' ' ')

if [ -n "$FILES" ]; then
    echo "[pre-commit] Running Prettier..."
    npx prettier --check $FILES

    echo "[pre-commit] Running ESLint..."
    npx eslint --no-warn-ignored $FILES
fi

echo "[pre-commit] Running Test Suite..."
npm test

echo "[pre-commit] All checks passed!"
